"""Verified product photo URLs for the offline catalogue.

GENERATED FILE -- do not edit by hand.
Regenerate with:  python tools/resolve_images.py

Every URL here returned a real image body when this file was written.
Parts without an entry fall back to the drawn package outline in the UI,
and any URL that later goes dead does the same at render time.
"""

PART_IMAGES = {
    'ADS1115IDGSR': 'https://www.ti.com/graphics/folders/partimages/ADS1115.jpg',
    'ADS1256IDBR': 'https://www.ti.com/graphics/folders/partimages/ADS1256.jpg',
    'ADS8688IDBTR': 'https://www.ti.com/graphics/folders/partimages/ADS8688.jpg',
    'AM3358BZCZA100': 'https://www.ti.com/graphics/folders/partimages/AM3358.jpg',
    'AMC1200SDUBR': 'https://www.ti.com/graphics/folders/partimages/AMC1200.jpg',
    'AMC1301DWVR': 'https://www.ti.com/graphics/folders/partimages/AMC1301.jpg',
    'BQ24074RGTR': 'https://www.ti.com/graphics/folders/partimages/BQ24074.jpg',
    'BQ76952PFBR': 'https://www.ti.com/graphics/folders/partimages/BQ76952.jpg',
    'CC1101RGPR': 'https://www.ti.com/graphics/folders/partimages/CC1101.jpg',
    'CC2652R1FRGZR': 'https://www.ti.com/graphics/folders/partimages/CC2652R.jpg',
    'CD4017BE': 'https://www.ti.com/graphics/folders/partimages/CD4017B.jpg',
    'CD4051BE': 'https://www.ti.com/graphics/folders/partimages/CD4051B.jpg',
    'CD74HC4067M96': 'https://www.ti.com/graphics/folders/partimages/CD74HC4067.jpg',
    'CDCE913PWR': 'https://www.ti.com/graphics/folders/partimages/CDCE913.jpg',
    'DLP3010FQF': 'https://www.ti.com/graphics/folders/partimages/DLP3010.jpg',
    'DLPA2005RTQR': 'https://www.ti.com/graphics/folders/partimages/DLPA2005.jpg',
    'DLPC3439FZEZ': 'https://www.ti.com/graphics/folders/partimages/DLPC3439.jpg',
    'DRV2605LDGSR': 'https://www.ti.com/graphics/folders/partimages/DRV2605L.jpg',
    'DRV8313PWPR': 'https://www.ti.com/graphics/folders/partimages/DRV8313.jpg',
    'DRV8825PWPR': 'https://www.ti.com/graphics/folders/partimages/DRV8825.jpg',
    'DS90C401M': 'https://www.ti.com/graphics/folders/partimages/DS90C401.jpg',
    'HDC1080DMBR': 'https://www.ti.com/graphics/folders/partimages/HDC1080.jpg',
    'INA117P': 'https://www.ti.com/graphics/folders/partimages/INA117.jpg',
    'INA128P': 'https://www.ti.com/graphics/folders/partimages/INA128.jpg',
    'INA132UA': 'https://www.ti.com/graphics/folders/partimages/INA132.jpg',
    'INA149AIDR': 'https://www.ti.com/graphics/folders/partimages/INA149.jpg',
    'INA180A1IDBVR': 'https://www.ti.com/graphics/folders/partimages/INA180.jpg',
    'INA181A1IDBVR': 'https://www.ti.com/graphics/folders/partimages/INA181.jpg',
    'INA219AIDR': 'https://www.ti.com/graphics/folders/partimages/INA219.jpg',
    'INA226AIDGSR': 'https://www.ti.com/graphics/folders/partimages/INA226.jpg',
    'INA228AIDGSR': 'https://www.ti.com/graphics/folders/partimages/INA228.jpg',
    'INA240A2PWR': 'https://www.ti.com/graphics/folders/partimages/INA240.jpg',
    'INA250A2PW': 'https://www.ti.com/graphics/folders/partimages/INA250A2.jpg',
    'INA253A2PWR': 'https://www.ti.com/graphics/folders/partimages/INA253.jpg',
    'INA260AIPWR': 'https://www.ti.com/graphics/folders/partimages/INA260.jpg',
    'INA3221AIRGVR': 'https://www.ti.com/graphics/folders/partimages/INA3221.jpg',
    'INA333AIDGKR': 'https://www.ti.com/graphics/folders/partimages/INA333.jpg',
    'ISO124U': 'https://www.ti.com/graphics/folders/partimages/ISO124.jpg',
    'ISO7741DWR': 'https://www.ti.com/graphics/folders/partimages/ISO7741.jpg',
    'LM13700N': 'https://www.ti.com/graphics/folders/partimages/LM13700.jpg',
    'LM1881N': 'https://www.ti.com/graphics/folders/partimages/LM1881.jpg',
    'LM2596S-ADJ': 'https://www.ti.com/graphics/folders/partimages/LM2596.jpg',
    'LM324N': 'https://www.ti.com/graphics/folders/partimages/LM324.jpg',
    'LM339N': 'https://www.ti.com/graphics/folders/partimages/LM339.jpg',
    'LM358P': 'https://www.ti.com/graphics/folders/partimages/LM358.jpg',
    'LM393P': 'https://www.ti.com/graphics/folders/partimages/LM393.jpg',
    'LM675T': 'https://www.ti.com/graphics/folders/partimages/LM675.jpg',
    'LM7805CT': 'https://www.ti.com/graphics/folders/partimages/LM7805C.jpg',
    'LMH3401IRMZT': 'https://www.ti.com/graphics/folders/partimages/LMH3401.jpg',
    'LMH5401IRMST': 'https://www.ti.com/graphics/folders/partimages/LMH5401.jpg',
    'LMH6552MA': 'https://www.ti.com/graphics/folders/partimages/LMH6552.jpg',
    'LMH6702MA': 'https://www.ti.com/graphics/folders/partimages/LMH6702.jpg',
    'LOG112AID': 'https://www.ti.com/graphics/folders/partimages/LOG112.jpg',
    'LOG114AIRGVT': 'https://www.ti.com/graphics/folders/partimages/LOG114.jpg',
    'MSP430G2553IN20': 'https://www.ti.com/graphics/folders/partimages/MSP430G2553.jpg',
    'NE5532P': 'https://www.ti.com/graphics/folders/partimages/NE5532.jpg',
    'NE555P': 'https://www.ti.com/graphics/folders/partimages/NE555.jpg',
    'ONET1191PRGTR': 'https://www.ti.com/graphics/folders/partimages/ONET1191P.jpg',
    'OPA1612AIDR': 'https://www.ti.com/graphics/folders/partimages/OPA1612.jpg',
    'OPA189IDBVR': 'https://www.ti.com/graphics/folders/partimages/OPA189.jpg',
    'OPA2134PA': 'https://www.ti.com/graphics/folders/partimages/OPA2134.jpg',
    'OPA2188AIDR': 'https://www.ti.com/graphics/folders/partimages/OPA2188.jpg',
    'OPA277PA': 'https://www.ti.com/graphics/folders/partimages/OPA277.jpg',
    'OPA361AIDCKR': 'https://www.ti.com/graphics/folders/partimages/OPA361.jpg',
    'OPA541AP': 'https://www.ti.com/graphics/folders/partimages/OPA541.jpg',
    'OPA548T': 'https://www.ti.com/graphics/folders/partimages/OPA548.jpg',
    'OPA695IDBVR': 'https://www.ti.com/graphics/folders/partimages/OPA695.jpg',
    'OPA855IDSGT': 'https://www.ti.com/graphics/folders/partimages/OPA855.jpg',
    'OPA857IRGTT': 'https://www.ti.com/graphics/folders/partimages/OPA857.jpg',
    'OPA858IDSGT': 'https://www.ti.com/graphics/folders/partimages/OPA858.jpg',
    'OPA860ID': 'https://www.ti.com/graphics/folders/partimages/OPA860.jpg',
    'PCM5102APWR': 'https://www.ti.com/graphics/folders/partimages/PCM5102A.jpg',
    'PGA113AIDGSR': 'https://www.ti.com/graphics/folders/partimages/PGA113.jpg',
    'PGA281AIPW': 'https://www.ti.com/graphics/folders/partimages/PGA281.jpg',
    'RCV420JP': 'https://www.ti.com/graphics/folders/partimages/RCV420.jpg',
    'SHC615AU': 'https://www.ti.com/graphics/folders/partimages/SHC615.jpg',
    'SN65HVD230DR': 'https://www.ti.com/graphics/folders/partimages/SN65HVD230.jpg',
    'SN65HVD72DR': 'https://www.ti.com/graphics/folders/partimages/SN65HVD72.jpg',
    'SN65LVDS1DBVR': 'https://www.ti.com/graphics/folders/partimages/SN65LVDS1.jpg',
    'SN74HC08N': 'https://www.ti.com/graphics/folders/partimages/SN74HC08.jpg',
    'SN74LVC245APWR': 'https://www.ti.com/graphics/folders/partimages/SN74LVC245A.jpg',
    'THS3491IDDAR': 'https://www.ti.com/graphics/folders/partimages/THS3491.jpg',
    'THS4521IDGKR': 'https://www.ti.com/graphics/folders/partimages/THS4521.jpg',
    'THS4551IDGKR': 'https://www.ti.com/graphics/folders/partimages/THS4551.jpg',
    'THS6012IDWP': 'https://www.ti.com/graphics/folders/partimages/THS6012.jpg',
    'THS7314D': 'https://www.ti.com/graphics/folders/partimages/THS7314.jpg',
    'TL072CP': 'https://www.ti.com/graphics/folders/partimages/TL072.jpg',
    'TLV3501AIDBVR': 'https://www.ti.com/graphics/folders/partimages/TLV3501.jpg',
    'TMP117AIDRVR': 'https://www.ti.com/graphics/folders/partimages/TMP117.jpg',
    'TMUX1208PWR': 'https://www.ti.com/graphics/folders/partimages/TMUX1208.jpg',
    'TPA3116D2DADR': 'https://www.ti.com/graphics/folders/partimages/TPA3116D2.jpg',
    'TPS22918DBVR': 'https://www.ti.com/graphics/folders/partimages/TPS22918.jpg',
    'TPS54331DR': 'https://www.ti.com/graphics/folders/partimages/TPS54331.jpg',
    'TPS62840DLCR': 'https://www.ti.com/graphics/folders/partimages/TPS62840.jpg',
    'TRF371135IRGZR': 'https://www.ti.com/graphics/folders/partimages/TRF371135.jpg',
    'TXS0108EPWR': 'https://www.ti.com/graphics/folders/partimages/TXS0108E.jpg',
    'VCA821IRGVT': 'https://www.ti.com/graphics/folders/partimages/VCA821.jpg',
    'VCA824IDGSR': 'https://www.ti.com/graphics/folders/partimages/VCA824.jpg',
    'XTR111AIDGQR': 'https://www.ti.com/graphics/folders/partimages/XTR111.jpg',
    'XTR116U': 'https://www.ti.com/graphics/folders/partimages/XTR116.jpg',
}


def for_part(mpn):
    """Product photo URL for a part number, or None."""
    return PART_IMAGES.get((mpn or '').strip())
